- type: dungeonConfig
  id: CaveFactory
  generator: !type:PrefabDunGen
    roomWhitelist:
      - CaveFactory
    presets:
      - Cross
      - SpaceMan
      - FourSquare
  postGeneration:
    - !type:MiddleConnectionPostGen
      overlapCount: 3
      count: 3
      entities:
        - CableApcExtension
        - AirlockEngineeringGlass
      edgeEntities:
        - Grille
        - Window

    - !type:MiddleConnectionPostGen
      count: 1
      entities:
        - CableApcExtension
        - AirlockEngineeringGlass

    - !type:EntrancePostGen
      count: 2
      entities:
        - AirlockEngineeringGlass

    - !type:InternalWindowPostGen
      entities:
        - Grille
        - Window

    - !type:ExternalWindowPostGen
      entities:
        - Grille
        - ReinforcedWindow

    - !type:WallMountPostGen
      spawns:
        # Posters
        - id: RandomPosterLegit
          orGroup: content
        - id: ExtinguisherCabinetFilled
          prob: 0.2
          orGroup: content
        - id: RandomPainting
          prob: 0.05
          orGroup: content
        - id: Intercom
          prob: 0.1
          orGroup: content

    - !type:BoundaryWallPostGen
      tile: FloorSteel
      wall: WallReinforced
      cornerWall: WallReinforced
